on:
  push:
    branches:    
      - master
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Setup Bun
        uses: xHyroM/setup-bun@v0.1.7
      - run: bun install
      - run: bun run build
      - name: Remove File
        uses: JesseTG/rm@v1.0.0
        with:
          path: .gitignore
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: .

    
      

      
